CREATE TABLE `videos`.`google_form_data` (

  `id`                  INT     NOT NULL AUTO_INCREMENT,
  `timestamp`           TEXT,
  `username`            TEXT,
  `file_name`           TEXT,
  `description`         TEXT,
  `teacher_count`       TEXT,
  `teacher_ethnicities` TEXT,
  `student_ethnicities` TEXT,
  `activities`          TEXT,
  `technical_issues`    TEXT,
  `start_1`             TEXT,
  `stop_1`              TEXT,
  `usage_1`             TEXT,
  `notes_1`             TEXT,
  `start_2`             TEXT,
  `stop_2`              TEXT,
  `usage_2`             TEXT,
  `notes_2`             TEXT,
  `start_3`             TEXT,
  `stop_3`              TEXT,
  `usage_3`             TEXT,
  `notes_3`             TEXT,
  `start_4`             TEXT,
  `stop_4`              TEXT,
  `usage_4`             TEXT,
  `notes_4`             TEXT,
  `start_5`             TEXT,
  `stop_5`              TEXT,
  `usage_5`             TEXT,
  `notes_5`             TEXT,
  `start_6`             TEXT,
  `stop_6`              TEXT,
  `usage_6`             TEXT,
  `notes_6`             TEXT,
  `start_7`             TEXT,
  `stop_7`              TEXT,
  `usage_7`             TEXT,
  `notes_7`             TEXT,
  `start_8`             TEXT,
  `stop_8`              TEXT,
  `usage_8`             TEXT,
  `notes_8`             TEXT,
  `start_9`             TEXT,
  `stop_9`              TEXT,
  `usage_9`             TEXT,
  `notes_9`             TEXT,
  `start_10`            TEXT,
  `stop_10`             TEXT,
  `usage_10`            TEXT,
  `notes_10`            TEXT,

  PRIMARY KEY (`id`)

) ENGINE=MyISAM DEFAULT CHARSET=utf8;
